#!/bin/bash
#
# This is a script for running a TripleA bot on a Unix-like system.
#
# To run this script, change to the directory in which you unpacked the
# headless game server archive, and type "./run_bot" and specifies options.
# Full usage details are found under --help, "./run_bot -h".
#

###############################################################################
# VARIABLE DEFAULTS START HERE
###############################################################################

#
# The TripleA username that owns the bot.
#
# This is a required variable. The default is empty string which will be replaced
# with the value passed into the script. The script will not run without a username.
#
USER=

#
# The folder from which the bot will load game maps.
#
# The default value is the folder in which the TripleA game client stores
# maps that it downloads.  Under normal circumstances, you will not have to
# change this variable.  However, if you customized the settings in your
# TripleA client to use a different maps folder, you should change this
# variable to refer to the same location.
#
# DO NOT CHANGE!!!
# This is set to the location of the software install.
#
MAPS_FOLDER="/opt/triplea/downloadedMaps"

#
# The port on which the bot will listen for connections.  This port must be
# reachable from the Internet, so you may have to configure your firewall
# appropriately.
#
# Under normal circumstances, you will not have to change this variable.
# However, if you choose to run multiple bots on your system, you need to
# select a different available port for each bot.
#
BOT_PORT=3300

#
# The name of the bot as displayed in the lobby.  Each bot must have a unique
# name.
#
# The default value uses a combination of your username and the local port
# you selected above on which the bot will run.  Under normal circumstances,
# you will not have to change this variable.
#
# Here the value is set to blank and later set to the default if an override is not
# provided through start options.
#
BOT_NAME=

#
# The password used to secure access to games running on your bot.  Users
# attempting to start a new game or connect to an existing game on your bot
# will be prompted for this password.  If the password is an empty string,
# the user will not be prompted, and any lobby user will be able to use your
# bot.
#
# The default value is an empty password. You should change this to a
# non-empty string if you do not want arbitrary users to use your bot.  For
# example, you may wish to run a private game for you and some friends.  In
# that case, set the password to a non-empty string and communicate it to
# your friends in some manner (e.g. via email).
#
BOT_PASSWORD=

#
# The hostname of the lobby to which the bot will connect.
#
# The default value is the hostname for the TripleA community's public lobby.
# Under normal circumstances, you will not have to change this variable.
#
LOBBY_URI="https://prod2-lobby.triplea-game.org"

#
# The password used to secure remote maintenance of your bot.  A lobby
# moderator who wishes to perform remote maintenance on your bot will be
# required to enter this password in order to complete any maintenance
# action.  If the password is an empty string, a lobby moderator will be able
# to perform remote maintenance on your bot without your permission.
#
# The default value is an empty password. You should change this to a
# non-empty string if you do not want lobby moderators to interfere with the
# operation of your bot.  Note that a lobby moderator that cannot perform
# remote maintenance of your bot may choose to boot your bot from the lobby.
#
LOBBY_SUPPORT_PASSWORD=

#
# The comment that shows in the game lobby. When left blank, TripleA will set this
# to the standard Bot comment.
#
LOBBY_GAME_COMMENTS=

###############################################################################
# VARIABLE DEFAULTS END HERE
#
# DO NOT MODIFY ANYTHING BELOW THIS LINE!
###############################################################################

display_usage() {
	echo -e "\nUsage:  run_bot <-u username> [OPTIONS]\n"
	echo -e "A TripleA bot runner"
	echo -e "\nOptions:"
	echo -e "   -b, --bot_name                  Name the bot uses in the lobby (default \"Bot_{username}_{port}\")"
	echo -e "   -c, --lobby_comment             The comment used in the lobby (default \"automated_host\")"
	echo -e "   -h, --help                      Display this help and exit"
	echo -e "   -l, --lobby                     Hostname of the lobby to which the bot will connect (default \"https://lobby.triplea-game.org\")"
	echo -e "   -L, --lobby_support_password    Lobby support password to secure remote maintenance (default is no password)"
	echo -e "   -P, --password                  Bot password to secure games running on bot (default is no password)"
	echo -e "   -p, --port                      Port to run the bot on (default 3300)"
	echo -e "   -u, --username                  Your TripleA Username"
	}

if [ $# = 0 ]; then
    display_usage
    exit
fi

while [ "$1" != "" ]; do
    case $1 in
        -b | --bot_name )       shift
                                BOT_NAME="$1"
                                ;;
        -c | --comment )        shift
                                LOBBY_GAME_COMMENTS="$1"
                                ;;
        -h | --help )           display_usage
                                exit
                                ;;
        -l | --lobby )          shift
                                LOBBY_URI="$1"
                                ;;
        -L | --lobby_support_password )       shift
                                              LOBBY_SUPPORT_PASSWORD="$1"
                                              ;;
        -P | --password )       shift
                                BOT_PASSWORD=$1
                                ;;
        -p | --port )           shift
                                BOT_PORT=$1
                                ;;
        -u | --username )       shift
                                USER="$1"
                                ;;
        * )                     display_usage
                                exit 1
    esac
    shift
done

if [ "$USER" = "" ]; then
  echo -e "\nERROR: The username cannot be blank.\n"
  display_usage
  exit
fi

if [ "$BOT_NAME" = "" ]; then
  BOT_NAME="Bot_${USER}_${BOT_PORT}"
fi

java \
    -server \
    -Xmx256M \
    -Djava.awt.headless=true \
    -jar /opt/bin/triplea-game-headless-*.jar \
    -Ptriplea.lobby.game.supportPassword="$LOBBY_SUPPORT_PASSWORD" \
    -Ptriplea.lobby.uri="$LOBBY_URI" \
    -Ptriplea.map.folder="$MAPS_FOLDER" \
    -Ptriplea.name="$BOT_NAME" \
    -Ptriplea.port="$BOT_PORT" \
    -Ptriplea.server.password="$BOT_PASSWORD" \
    -Ptriplea.lobby.game.comments="$LOBBY_GAME_COMMENTS" >/opt/triplea/savedGames/logs/log.txt 2>&1